[project]
name = "ims-mobile"
version = "1.0.2"
description = "IMS mobile companion"
requires-python = ">=3.12,<3.13"
dependencies = [
    "flet==0.86.5",
    "flet-camera==0.86.5",
    "flet-permission-handler",
    "requests",
    "numpy",
    "opencv-contrib-python==5.0.0.93",
]

[tool.flet]
permissions = ["camera"]

[tool.flet.android]
extract_packages = ["cv2"]

[tool.flet.android.permission]
"android.permission.CAMERA" = true

[tool.flet.android.feature]
"android.hardware.camera" = true
