name: Build IMS APK

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Python 3.12
        uses: actions/setup-python@v6
        with:
          python-version: "3.12"

      - name: Install Flet CLI
        run: |
          python -m pip install --upgrade pip
          python -m pip install flet-cli==0.86.5

      - name: Build release APK
        run: |
          flet build apk --python-version 3.12 --permissions camera

      - name: Show APK files
        run: |
          find . -type f -name "*.apk" -print

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: IMS-Android-APK
          path: build/**/*.apk
          if-no-files-found: error
